# Generated by Django 4.2.30 on 2026-06-01 18:49

import hashlib
import re

from django.db import migrations, models


def normalize_job_text(value):
    return re.sub(r"\s+", " ", re.sub(r"[^a-z0-9]+", " ", (value or "").lower())).strip()


def make_fingerprint(job):
    normalized = "|".join([
        normalize_job_text(job.title),
        normalize_job_text(job.company),
        normalize_job_text(job.location),
        normalize_job_text(job.description)[:1200],
    ])
    return hashlib.sha256(normalized.encode("utf-8")).hexdigest()


def backfill_fingerprints(apps, schema_editor):
    JobAdvert = apps.get_model("jobs", "JobAdvert")
    seen = {}
    for job in JobAdvert.objects.order_by("id"):
        fingerprint = make_fingerprint(job)
        if fingerprint in seen:
            job.delete()
            continue
        seen[fingerprint] = job.id
        job.fingerprint = fingerprint
        job.save(update_fields=["fingerprint"])


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_alter_jobadvert_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobadvert',
            name='fingerprint',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.RunPython(backfill_fingerprints, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='jobadvert',
            name='fingerprint',
            field=models.CharField(blank=True, db_index=True, max_length=64, unique=True),
        ),
        migrations.AddConstraint(
            model_name='jobadvert',
            constraint=models.UniqueConstraint(condition=models.Q(('external_id__isnull', False)), fields=('source', 'external_id'), name='unique_job_source_external_id'),
        ),
    ]
