from django.test import TestCase
from django.urls import reverse


class MethodologyPageTests(TestCase):
    def test_methodology_page_renders(self):
        response = self.client.get(reverse("methodology"))

        self.assertEqual(response.status_code, 200)
        self.assertContains(response, "Normalized Embeddings")
        self.assertContains(response, "Cosine similarity")
        self.assertContains(response, "\\cos(A, B)")
        self.assertContains(response, "\\operatorname{final}")
        self.assertContains(response, "School Skill Matrix Calculations")
        self.assertContains(response, "Demand evidence")
        self.assertContains(response, "NER Skill Evidence")
        self.assertContains(response, "BERT skill NER")
        self.assertContains(response, "fine-tuned DistilBERT")
        self.assertContains(response, "Decision tree ranking")
        self.assertContains(response, "AI Model Ensemble")
        self.assertContains(response, "Confidence Ranking")
        self.assertContains(response, "Preprocessing Boundary")
        self.assertContains(response, "Natural text preserved")
        self.assertContains(response, "Stop-word removal is avoided")
        self.assertContains(response, "Pipeline signal map")
        self.assertContains(response, "Preprocessing split diagram")
        self.assertContains(response, "Skill extraction model stack")
        self.assertContains(response, "Final score composition")
        self.assertContains(response, "Decision tree ranking example")
        self.assertContains(response, "Mini gap matrix visual")
        self.assertContains(response, "Data Export Views")
        self.assertContains(response, "End-to-End Iterative Pipeline")
        self.assertContains(response, "Review and feed back")
        self.assertContains(response, "methodologically, the workflow is circular")
        self.assertContains(response, "Pipeline + feedback loop")
        self.assertContains(response, "Visualise and export")
        self.assertContains(response, "Next analysis refresh")
        self.assertContains(response, "Back to Ingest Evidence")
        self.assertContains(response, "Reviewed skills and aliases are reloaded")
        self.assertContains(response, "Ingest Evidence")
        self.assertContains(response, "Clean and Deduplicate")
        self.assertContains(response, "Comparable signals")
        self.assertContains(response, "Actionable outputs")
        self.assertContains(response, "Skill Forecasting")
        self.assertContains(response, "Semantic Skill Clustering")
        self.assertContains(response, "Cross-tab heatmap")
        self.assertContains(response, "The number inside each cell is a count of job adverts")
        self.assertContains(response, "MathJax")
        self.assertContains(response, "Adzuna deduplication")
        self.assertContains(response, "CRISP-DM Data-Mining Framework")
        self.assertContains(response, "Cross Industry Standard Process for Data Mining")
        self.assertContains(response, "human-cleaned extraction knowledge")
        self.assertContains(response, "approved skill entities and approved aliases")
        self.assertContains(response, "hourly refresh can rerun reviewed aliases")
