# Generated by Django 4.2.30 on 2026-05-28 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0002_alter_analysisrun_id_alter_gapresult_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskrecord',
            name='task_id',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
