# Generated by Codex on 2026-05-28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("analysis", "0003_alter_taskrecord_task_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="taskrecord",
            name="progress",
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
