# Generated by Codex on 2026-06-09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("analysis", "0006_taskrecord_updated_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="gapresult",
            name="score_breakdown",
            field=models.JSONField(default=dict),
        ),
    ]
