# Generated by Codex on 2026-06-23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("analysis", "0007_gapresult_score_breakdown"),
    ]

    operations = [
        migrations.CreateModel(
            name="SkillAlias",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("canonical_skill", models.CharField(max_length=160)),
                ("alias", models.CharField(max_length=160)),
                ("status", models.CharField(choices=[("candidate", "Candidate"), ("approved", "Approved"), ("rejected", "Rejected")], default="candidate", max_length=20)),
                ("source", models.CharField(choices=[("manual", "Manual"), ("evidence", "Evidence"), ("human_review", "Human review"), ("import", "Import"), ("model_suggestion", "Model suggestion"), ("seed", "Seed")], default="evidence", max_length=30)),
                ("confidence", models.FloatField(default=0.0)),
                ("evidence_count", models.PositiveIntegerField(default=1)),
                ("created_from_text", models.TextField(blank=True)),
                ("created_from_doc_id", models.CharField(blank=True, max_length=120)),
                ("last_seen_at", models.DateTimeField(blank=True, null=True)),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["status", "-evidence_count", "canonical_skill", "alias"],
                "unique_together": {("canonical_skill", "alias")},
            },
        ),
    ]
