import json
from pathlib import Path

from django.conf import settings
from django.core.management.base import BaseCommand, CommandError
from django.utils import timezone

from analysis.models import TaskRecord
from analysis.services import run_gap_analysis
from jobs.models import JobAdvert, job_fingerprint


def normalize_skill_name(value):
    return " ".join(str(value or "").lower().replace("-", " ").split())


def normalize_entity(entity, default_source="notebook-import"):
    if not isinstance(entity, dict):
        skill = normalize_skill_name(entity)
        return {"skill": skill, "id": f"skill-{skill.replace(' ', '-')}", "source": default_source}

    skill = normalize_skill_name(entity.get("skill") or entity.get("text"))
    if not skill:
        return None
    normalized = dict(entity)
    normalized["skill"] = skill
    normalized.setdefault("id", f"skill-{skill.replace(' ', '-')}")
    normalized.setdefault("source", default_source)
    return normalized


class Command(BaseCommand):
    help = "Import notebook-generated job rows with extracted skills and optional embeddings."

    def add_arguments(self, parser):
        parser.add_argument(
            "input_path",
            nargs="?",
            default="imports/embedded_jobs/jobs_embedded.jsonl",
            help="Path to a JSONL or JSON file generated by a notebook.",
        )
        parser.add_argument(
            "--clear-notebook-jobs",
            action="store_true",
            help="Delete existing notebook-imported jobs before importing.",
        )
        parser.add_argument(
            "--run-analysis",
            action="store_true",
            help="Run gap analysis after import so the dashboard immediately sees a fresh AnalysisRun.",
        )
        parser.add_argument(
            "--run-name",
            default="Notebook Embedded Import Analysis",
            help="Analysis run name to use when --run-analysis is enabled.",
        )
        parser.add_argument(
            "--max-jobs",
            type=int,
            default=None,
            help="Optional cap for the number of jobs scored during analysis.",
        )

    def handle(self, *args, **options):
        input_path = Path(options["input_path"])
        if not input_path.is_absolute():
            input_path = Path(settings.BASE_DIR) / input_path
        if not input_path.exists():
            raise CommandError(f"Input file not found: {input_path}")

        records = self._load_records(input_path)
        if not records:
            raise CommandError(f"No records found in {input_path}")

        task = TaskRecord.objects.create(
            task_id=f"embedded-jobs:{input_path.name}",
            run_name=f"Import embedded jobs from {input_path.name}",
            status="STARTED",
            progress=5,
            notes="Preparing embedded notebook import...",
        )

        try:
            if options["clear_notebook_jobs"]:
                deleted, _ = JobAdvert.objects.filter(source="csv", external_id__startswith="notebook-").delete()
                task.progress = 10
                task.notes = f"Cleared {deleted} previous notebook-imported jobs."
                task.save(update_fields=["progress", "notes", "updated_at"])

            saved, updated, skipped = self._upsert_records(records)
            summary = f"Imported {saved} new jobs, updated {updated}, skipped {skipped} from {input_path.name}."

            if not options["run_analysis"]:
                TaskRecord.objects.filter(id=task.id).update(
                    status="SUCCESS",
                    progress=100,
                    notes=summary,
                    finished_at=timezone.now(),
                    updated_at=timezone.now(),
                )
                self.stdout.write(self.style.SUCCESS(summary))
                return

            TaskRecord.objects.filter(id=task.id).update(
                status="STARTED",
                progress=55,
                notes=summary + " Running analysis...",
                updated_at=timezone.now(),
            )
            self.stdout.write(self.style.SUCCESS(summary))
            self.stdout.write("Running gap analysis for dashboard data...")

            def report(percent, message):
                mapped = 55 + int(45 * max(0, min(100, percent)) / 100)
                TaskRecord.objects.filter(id=task.id).update(
                    status="STARTED",
                    progress=mapped,
                    notes=message,
                    updated_at=timezone.now(),
                )
                self.stdout.write(message)

            run = run_gap_analysis(
                run_name=options["run_name"],
                progress_callback=report,
                max_jobs=options["max_jobs"],
            )
            final_notes = f"{summary} Analysis run #{run.id} completed with status {run.status}."
            TaskRecord.objects.filter(id=task.id).update(
                status="SUCCESS",
                progress=100,
                notes=final_notes,
                finished_at=timezone.now(),
                updated_at=timezone.now(),
            )
            self.stdout.write(self.style.SUCCESS(final_notes))
        except Exception:
            TaskRecord.objects.filter(id=task.id).update(
                status="FAILURE",
                finished_at=timezone.now(),
                updated_at=timezone.now(),
            )
            raise

    def _load_records(self, input_path):
        if input_path.suffix.lower() == ".jsonl":
            records = []
            for line in input_path.read_text(encoding="utf-8").splitlines():
                if line.strip():
                    records.append(json.loads(line))
            return records
        if input_path.suffix.lower() == ".json":
            payload = json.loads(input_path.read_text(encoding="utf-8"))
            if isinstance(payload, list):
                return payload
            if isinstance(payload, dict) and isinstance(payload.get("records"), list):
                return payload["records"]
        raise CommandError("Input must be a .jsonl file or a .json file containing a list or {'records': [...]} payload.")

    def _upsert_records(self, records):
        saved = 0
        updated = 0
        skipped = 0

        for index, row in enumerate(records, start=1):
            title = str(row.get("title") or "").strip()
            description = str(row.get("description") or "").strip()
            if not title or not description:
                skipped += 1
                continue

            external_id = str(row.get("external_id") or f"notebook-{index:06d}")
            company = str(row.get("company") or "").strip()
            recruiter = str(row.get("recruiter") or "").strip()
            location = str(row.get("location") or "").strip()
            job_reference = str(row.get("job_reference") or "").strip()
            category = str(row.get("category") or "").strip()
            summary = str(row.get("summary") or "").strip()
            position_info = str(row.get("position_info") or "").strip()

            skills = sorted({
                normalize_skill_name(skill)
                for skill in (row.get("skills_extracted") or [])
                if normalize_skill_name(skill)
            })
            entities = []
            for raw_entity in (row.get("skill_entities") or []):
                entity = normalize_entity(raw_entity)
                if entity:
                    entities.append(entity)
            if not entities and skills:
                entities = [normalize_entity({"skill": skill}) for skill in skills]

            vector = row.get("vector") or []
            if vector and not isinstance(vector, list):
                raise CommandError(f"Row {index} has a non-list vector.")

            cleaned_payload = row.get("cleaned_payload") or {}
            if cleaned_payload and not isinstance(cleaned_payload, dict):
                raise CommandError(f"Row {index} has a non-dict cleaned_payload.")

            fingerprint = row.get("fingerprint") or job_fingerprint(
                title,
                company,
                location,
                description,
                recruiter,
                job_reference,
            )

            defaults = {
                "title": title[:255],
                "company": company[:255],
                "recruiter": recruiter[:255],
                "job_reference": job_reference[:255],
                "location": location[:255],
                "category": category[:255],
                "contract_type": str(row.get("contract_type") or "")[:80],
                "contract_time": str(row.get("contract_time") or "")[:80],
                "summary": summary,
                "position_info": position_info,
                "raw_description": description,
                "description": description,
                "url": str(row.get("url") or "")[:500],
                "source": "csv",
                "fingerprint": fingerprint,
                "salary_min": row.get("salary_min"),
                "salary_max": row.get("salary_max"),
                "skills_extracted": skills,
                "skill_entities": entities,
                "vector": vector,
                "cleaned_payload": cleaned_payload,
                "source_payload": row.get("source_payload") or {},
            }

            obj, created = JobAdvert.objects.update_or_create(
                source="csv",
                external_id=external_id,
                defaults=defaults,
            )
            if created:
                saved += 1
            else:
                updated += 1

        return saved, updated, skipped
